param(
    [string]$CoverageFile = "coverage_latest.cobertura.xml",
    [string]$TrxFile = "MultiMap.Tests/TestResults/net10-results.trx",
    [string]$OutputFile = "Docs/GeneratedTestingSummary.md"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-Percent {
    param(
        [double]$Numerator,
        [double]$Denominator
    )

    if ($Denominator -le 0) {
        return "0.0"
    }

    return [math]::Round(($Numerator / $Denominator) * 100, 1).ToString("0.0")
}

if (-not (Test-Path -LiteralPath $CoverageFile)) {
    throw "Coverage file not found: $CoverageFile"
}

if (-not (Test-Path -LiteralPath $TrxFile)) {
    throw "TRX file not found: $TrxFile"
}

[xml]$coverage = Get-Content -LiteralPath $CoverageFile
[xml]$trx = Get-Content -LiteralPath $TrxFile

$lineValid = [double]$coverage.coverage.'lines-valid'
$lineCovered = [double]$coverage.coverage.'lines-covered'
$branchValid = [double]$coverage.coverage.'branches-valid'
$branchCovered = [double]$coverage.coverage.'branches-covered'

$allMethods = $coverage.SelectNodes('//method')
$methodValid = $allMethods.Count
$methodCovered = ($allMethods | Where-Object { [double]$_.'line-rate' -gt 0 }).Count

$linePct = Get-Percent -Numerator $lineCovered -Denominator $lineValid
$branchPct = Get-Percent -Numerator $branchCovered -Denominator $branchValid
$methodPct = Get-Percent -Numerator $methodCovered -Denominator $methodValid

$counters = $trx.TestRun.ResultSummary.Counters
$totalTests = [int]$counters.total
$executedTests = [int]$counters.executed
$passedTests = [int]$counters.passed
$failedTests = [int]$counters.failed

$generatedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss K")

$markdown = @"
## Generated Test Summary

Last generated: $generatedAt

| Metric | Value |
|---|---|
| Total tests | $totalTests |
| Executed tests | $executedTests |
| Passed tests | $passedTests |
| Failed tests | $failedTests |
| Line coverage | $linePct% ($lineCovered / $lineValid) |
| Branch coverage | $branchPct% ($branchCovered / $branchValid) |
| Method coverage | $methodPct% ($methodCovered / $methodValid) |

> Generated by `scripts/Update-TestingSummary.ps1` from local test artifacts.
"@

$outputDirectory = Split-Path -Path $OutputFile -Parent
if (-not [string]::IsNullOrWhiteSpace($outputDirectory) -and -not (Test-Path -LiteralPath $outputDirectory)) {
    New-Item -Path $outputDirectory -ItemType Directory | Out-Null
}

Set-Content -LiteralPath $OutputFile -Value $markdown -Encoding UTF8
Write-Host "Generated testing summary: $OutputFile"
